# Generated by Django 3.1 on 2020-08-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_listpage'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventListPage',
            fields=[
                ('listpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.listpage')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.listpage',),
        ),
    ]
