# Generated by Django 3.1 on 2020-08-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventlistpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpage',
            options={'ordering': ['start_date']},
        ),
    ]
