version: "2"
services:
  web:
    build:
      context: .
    restart: always
    volumes:
      - ./:/code/
      - static-content:/code/static
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=
      - SECRET_KEY=
      - DB_NAME=
      - DB_USER=
      - DB_PASSWORD=
      - DB_HOST=
      - GA_TOKEN=
      - BASE_URL=
      - WAGTAIL_SITE_NAME=
      - AWS_STORAGE_BUCKET_NAME=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=

  nginx:
    image: nginx
    restart: always
    volumes:
      - static-content:/code/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8001:80"
    links:
      - web
    depends_on:
      - web

volumes:
  static-content:
