# Generated by Django 3.1 on 2020-08-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_listpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscpage',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
