# Generated by Django 3.1 on 2020-08-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('pages', '0005_auto_20200827_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Banner background image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
