# Generated by Django 3.1 on 2020-08-27 00:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('banner', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('short_text', wagtail.core.blocks.CharBlock()), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.RichTextBlock())])), ('form', wagtail.core.blocks.StructBlock([('publish_url', wagtail.core.blocks.URLBlock())])), ('buttons', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('buttons', wagtail.core.blocks.StreamBlock([('button', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock())]))]))]))], null=True),
        ),
    ]
